### ISSUE TITLE
[Punaises - DevOps] Automatisation workflow de développement et déploiement

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/stop-punaises#49]
## TODO :
- [x] @tristanrobert Créer le repository sur github stop-punaises et les différentes intégrations pour la CI (sonar-cloud, git guardian, etc..)

- [x]  @tristanrobert Créer et configurer le sous-domaine  stop-punaises.beta.gouv.fr
- [x]  @tristanrobert Créer les applications de staging et production

- Création du socle tecnhique du projet symfony 6
- Mise en place du monitoring d'erreur via sentry
- Mise en place de la pipeline d'intégration continue github-action 
- Créer les mailings-list d'email pour stop-punaises 
- Créer et configurer le bucket stockage object S3 sur OVH Cloud
